### ISSUE TITLE
Skill: (2) Use and organize SCSS in Rails

### ISSUE THREAD

**Issue by brauerbl** [brauerbl/tc359_rails_final#3]
@chrisvfritz
I think I've completed this skill. 

I realize I have quite a bit of nesting in the _nav.scss file and I've heard that's generally not recommended but I don't find it to cause any problems and it's easier to read in my opinion. Please let me know if you think I have an issue of excessive nesting.

**Comment by chrisvfritz** [comment]
I agree with your use of nesting in this case. Great job! :+1: This is one of the only SCSS implementations I've approved on the first round. Excellent attention to detail. :tada: :balloon:

**Comment by chrisvfritz** [comment]
And... that also adds up to 4.0 with my math. :tada: :balloon: :shipit: :metal:
